# Generated by Django 4.0.5 on 2022-06-07 11:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('age', models.IntegerField()),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Adopted', 'Adopted'), ('Under Consideration', 'Under Consideration')], max_length=100)),
                ('photoUrl', models.CharField(max_length=254)),
            ],
        ),
    ]
